### ISSUE TITLE
Avro generation failed with enums containing values with special characters

### ISSUE THREAD

**Issue by pfr-enedis** [FasterXML/jackson-dataformats-binary#422]
Enums with '-' characters in values,  fails
 
```
public enum EnumTypeContrat {
        CARD_S("CARD-S"),
        CARD_ELD("CARD-ELD"),
        GRD_F("GRD-F"),
        CSD("CSD"),
        GRD_RE("GRD-RE"),
        PROTOC_501("PROTOC-501"),
        CRAE("CRAE"),
        CARD_I("CARD-I"),
        CSD_I("CSD-I");

        private final String value;

        EnumTypeContrat(String value) {
            this.value = value;
        }
}
```

The error is : 

```
org.apache.avro.SchemaParseException: Illegal character in: CARD-S
	at org.apache.avro.Schema.validateName(Schema.java:1566)
	at org.apache.avro.Schema.access$400(Schema.java:91)
	at org.apache.avro.Schema$Field.<init>(Schema.java:546)
	at org.apache.avro.Schema$Field.<init>(Schema.java:585)
	at com.fasterxml.jackson.dataformat.avro.schema.RecordVisitor.schemaFieldForWriter(RecordVisitor.java:189)
	at com.fasterxml.jackson.dataformat.avro.schema.RecordVisitor.optionalProperty(RecordVisitor.java:117)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.depositSchemaProperty(BeanPropertyWriter.java:843)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:914)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:565)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4670)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4649)
```

are there any reason for checking the enum value ? as it is generated as an avro string ?

**Comment by cowtowncoder** [comment]
Please include actual code you are using: textual description is not enough to know what is being attempted.

Note, though, that the exception comes from Apache Avro library which does validation for generated schema.

**Comment by pfr-enedis** [comment]
Hi, @cowtowncoder , here is the reproductible example, 
it seems the reproduction behaviour, is more linked to the JsonValue annotation, 
when commenting this annotation, this work, and fail if the annotation is present


import java.util.HashMap;
import java.util.Map;

import javax.annotation.processing.Generated;

import org.junit.Test;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.dataformat.avro.AvroMapper;
import com.fasterxml.jackson.dataformat.avro.jsr310.AvroJavaTimeModule;
import com.fasterxml.jackson.dataformat.avro.schema.AvroSchemaGenerator;


/**
 * class to reproduce an avro error, for jackson databind
 */
public class GenerateAvroError {

    @Generated("jsonschema2pojo")
    public enum EnumTypeContrat {

        CARD_S("CARD-S"),
        CARD_ELD("CARD-ELD"),
        GRD_F("GRD-F"),
        CSD("CSD"),
        GRD_RE("GRD-RE"),
        PROTOC_501("PROTOC-501"),
        CRAE("CRAE"),
        CARD_I("CARD-I"),
        CSD_I("CSD-I");
        private final String value;
        private final static Map<String, EnumTypeContrat> CONSTANTS = new HashMap<String,EnumTypeContrat>();

        static {
            for (EnumTypeContrat c: values()) {
                CONSTANTS.put(c.value, c);
            }
        }

        EnumTypeContrat(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return this.value;
        }

        @JsonValue
        public String value() {
            return this.value;
        }

        @JsonCreator
        public static EnumTypeContrat fromValue(String value) {
            EnumTypeContrat constant = CONSTANTS.get(value);
            if (constant == null) {
                throw new IllegalArgumentException(value);
            } else {
                return constant;
            }
        }

    }

	public static class DummyClassToReproduceError {

		private EnumTypeContrat contract;

		@JsonProperty("contr")
		public EnumTypeContrat getContract() {
			return contract;
		}

	}
	

	@Test
	public void testSerializeAvro() throws Exception {

		AvroSchemaGenerator gen = new AvroSchemaGenerator();

		AvroMapper avroMapper = AvroMapper.builder().disable(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY)
				.addModule(new AvroJavaTimeModule()).build();

		gen.enableLogicalTypes();
		avroMapper.acceptJsonFormatVisitor(DummyClassToReproduceError.class, gen);
		com.fasterxml.jackson.dataformat.avro.AvroSchema schemaWrapper = gen.getGeneratedSchema();

		org.apache.avro.Schema avroSchema = schemaWrapper.getAvroSchema();
		String avroSchemaInJSON = avroSchema.toString(true);

		System.out.println(avroSchemaInJSON);
		
	}
	
	
}

**Comment by cowtowncoder** [comment]
Thank you @pfr-enedis for the reproduction.

**Comment by cowtowncoder** [comment]
@pfr-enedis Quick question: do you think new `AvroSchemaGenerator` configuration option added via #494 would solve the issue? Problem here is, I think, two-fold:

1. Since Enums are expressed as Java Strings otherwise (with JSON and many other formats), `@JsonValue` returning String isn't considered to change type from `Enum` to some other type, so type is generated as Avro Enum
2. Avro Enum names have somewhat strict validity rules

But with `AvroSchemaGenerator.enableWriteEnumAsString()` would change actual Avro type used.

@MichalFoksa WDYT?

**Comment by MichalFoksa** [comment]
With `AvroSchemaGenerator.enableWriteEnumAsString()` Avro type for `EnumTypeContrat` is string and the test above works. 

```
schema:
{
  "type" : "record",
  "name" : "DummyClassToReproduceError",
  "namespace" : "com.fasterxml.jackson.dataformat.avro.Issue422Test",
  "fields" : [ {
    "name" : "contr",
    "type" : [ "null", {
      "type" : "string",
      "java-class" : "com.fasterxml.jackson.dataformat.avro.Issue422Test$EnumTypeContrat"
    } ]
  } ]
}

**Comment by cowtowncoder** [comment]
@MichalFoksa excellent! Going forward it might be good to have a way to target specific classes (new annotation?), but for now I think this should be fine.

**Comment by cowtowncoder** [comment]
May close in near future as there is a work-around, but will first see if there's a way to handle error in better way.

**Comment by cowtowncoder** [comment]
Improved error handling; will close this issue. New issue(s) may be filed for suggesting further improvements.
