### ISSUE TITLE
Update to Avro 1.12.1 (Jackson 3.x only)

### ISSUE THREAD

**Issue by rdifrango** [FasterXML/jackson-dataformats-binary#514]
We were attempting to upgrade our project to Avro 1.12.0 with `jackson-dataformat-avro` version `2.17.2`

The failure I get is as follows:

```
Exception in thread "main" java.lang.NoSuchMethodError: 'org.apache.avro.Schema$Parser org.apache.avro.Schema$Parser.setValidate(boolean)'
	at com.fasterxml.jackson.dataformat.avro.AvroMapper.schemaFrom(AvroMapper.java:240)
	at com.fmr.difrango.ztester.DemoJacksonAvroFailure.main(DemoJacksonAvroFailure.java:23)
```

To demonstrate this, I created the following example program that uses [issue19.avsc](https://github.com/FasterXML/jackson-dataformats-binary/blob/2.18/avro/src/test/resources/com/fasterxml/jackson/dataformat/avro/issue19.avsc) as the schema to load.

```
package com.difrango.ztester;

import com.fasterxml.jackson.dataformat.avro.AvroMapper;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;

public class DemoJacksonAvroFailure {
    private static final Logger LOGGER = LoggerFactory.getLogger(DemoJacksonAvroFailure.class);

    public static void main(String[] args) {
        var expectedStream =
                DemoJacksonAvroFailure.class.getClassLoader().getResourceAsStream("issue19.avsc");

        var mapper = new AvroMapper();
        mapper.registerModule(new Jdk8Module());
        mapper.registerModule(new JavaTimeModule());

        try {
            var expected = mapper.schemaFrom(expectedStream);
        } catch (IOException e) {
            LOGGER.error("Error Handling the Schema", e);
        }
    }
}
```

**Comment by cowtowncoder** [comment]
Yes, see #167 -- you cannot upgrade Jackson 2.17 and below to Avro library past 1.8.2.

But upcoming 2.18.0 should allow upgrade.

**Comment by rdifrango** [comment]
Thanks @cowtowncoder.  It's interesting that we've been successfully using AVRO 1.11.2 so it must be some edge cases that we aren't currently hitting.

**Comment by cowtowncoder** [comment]
@rdifrango Ah. I forgot that the issue wrt upgrade were mostly in unit tests, not on binary compatibility between module and codec library.

But I hope 2.18.0-rc1 -- being released today! -- will work with 1.12.x and above.

**Comment by cowtowncoder** [comment]
2.18.0-rc1 now released: @rdifrango not sure if it's easy to do, but it'd be great to see if upgrade would work with 2.18, for eventual 2.18.0 release

**Comment by rdifrango** [comment]
> 2.18.0-rc1 now released: @rdifrango not sure if it's easy to do, but it'd be great to see if upgrade would work with 2.18, for eventual 2.18.0 release

I just tested it and I am seeing the same issue.

**Comment by cowtowncoder** [comment]
@rdifrango rats. Ok. That may also explain why upgrade was to `1.11.3` not `1.12.0`.

**Comment by rdifrango** [comment]
> @rdifrango rats. Ok. That may also explain why upgrade was to `1.11.3` not `1.12.0`.

Quite possibly...and I'll grant that the move to `1.12.0` is not backwards compatible.

**Comment by cowtowncoder** [comment]
It seems odd for Avro library to nominally follow SemVer but... seemingly not?
(although as a library maintainer I understand how difficult backwards-compatibility is).

But would be good to know why the method was removed & if it had been at least deprecated earlier. Plus whether there might be replacement to use, from older versions too.

**Comment by rdifrango** [comment]
> It seems odd for Avro library to nominally follow SemVer but... seemingly not? (although as a library maintainer I understand how difficult backwards-compatibility is).
> 
> But would be good to know why the method was removed & if it had been at least deprecated earlier. Plus whether there might be replacement to use, from older versions too.

I'd agree @cowtowncoder especially since I'm having a conversation with on [this PR](https://github.com/apache/commons-validator/pull/53) with the commons-validator team and they are being very strict.

I did look over on the avro side, but couldn't find any specific mention of why this was changed and it was unclear to me if it's now simply the default behavior of the parser or not.

Should we ask over there as well?

**Comment by cowtowncoder** [comment]
@rdifrango I guess damage is done, API compatibility broken b/w versions. So not sure how much value there would be.
(not sure how `commons-validator` is related -- is that a dependency they added/removed?)

**Comment by rdifrango** [comment]
> @rdifrango I guess damage is done, API compatibility broken b/w versions. So not sure how much value there would be. (not sure how `commons-validator` is related -- is that a dependency they added/removed?)

agreed the damage is done, the commons-validator was more an indicator that other apache projects seem to hold to strict guidelines around binary and API compatibility which clearly Avro has not.

**Comment by cowtowncoder** [comment]
One other reason why we probably cannot upgrade: looks like Avro 1.12.0 is built with JDK 11, and Jackson 2.18 still has Java 8 as the baseline.

**Comment by rdifrango** [comment]
> One other reason why we probably cannot upgrade: looks like Avro 1.12.0 is built with JDK 11, and Jackson 2.18 still has Java 8 as the baseline.

That definitely makes this tricky, any thoughts on a path forward?

**Comment by cowtowncoder** [comment]
@rdifrango No idea short-term. Things are tricky as it's multi-module Maven project so would need to at least build all with JDK 11; but then try to target JDK 8 (if even possible) for non-Avro backends.

But on very short term I think baseline code needs to remain 1.11.x.

Ideally we would let users override with newer version tho.

And I think it'd actually be possible to use matrix build for CI testing to try version override, if we get module itself run against newer library version -- but that's not solved yet; how to avoid/change `parser.setValidate()` call.

**Comment by cowtowncoder** [comment]
One quick note: Jackson 3.0 (from `master` branch) will have JDK 17 (at least) as baseline, so dependency could be increased there without problems. While that won't be released until maybe 2025/march (first Release Candidate), it'd be useful upgrade, if anyone could create a PR.

**Comment by cowtowncoder** [comment]
Ok, so Avro lib backwards-compatibility is really... not. There isn't any. 1.11.3 -> 1.11.4 breaks tests, as per #539. Patches can be as breaking as minor version or so.

**Comment by rdifrango** [comment]
> One quick note: Jackson 3.0 (from `master` branch) will have JDK 17 (at least) as baseline, so dependency could be increased there without problems. While that won't be released until maybe 2025/march (first Release Candidate), it'd be useful upgrade, if anyone could create a PR.
> 
> 

I'll try to take this on but it won't be until mid-January.

**Comment by cowtowncoder** [comment]
I think upgrading `master`/3.0 first to 1.12.x makes most sense.

Patch 1.11.4 is something users can opt-in regardless of what Jackson 2.x module defaults to (that is, for versions that default to 1.11.3, 2.18.x and 2.19)

**Comment by rdifrango** [comment]
> > One quick note: Jackson 3.0 (from `master` branch) will have JDK 17 (at least) as baseline, so dependency could be increased there without problems. While that won't be released until maybe 2025/march (first Release Candidate), it'd be useful upgrade, if anyone could create a PR.
> 
> I'll try to take this on but it won't be until mid-January.

ok, I started looking at this and it seems to break a few of the tests.  The two groups in particular `Jackson to Apache with Jackson schema` and `Apache to Apache with Jackson schema`.

In the one test `ListWithPrimitiveWrapperTest.testListWithShorts` it's complaining about `java.lang.ClassCastException: class java.lang.Short cannot be cast to class java.lang.Integer (java.lang.Short and java.lang.Integer are in module java.base of loader 'bootstrap')`

I'm just trying to understand these tests before moving forward.

**Comment by rdifrango** [comment]
and related, in ListWithPrimitiveWrapperTest.testListWithDoubles I'm getting the following in those same 2 tests:

>org.junit.ComparisonFailure: 
Expected :[1.0, 0.0, -1.0, 4.9E-324, 1.7976931348623157E308]
Actual   :[1.0, 0.0, -1.0, 0.0, Infinity]

**Comment by cowtowncoder** [comment]
@rdifrango Latter def sounds like `Float` used for `Double` (or vice versa), triggering over-/underflow.

**Comment by rdifrango** [comment]
> @rdifrango Latter def sounds like `Float` used for `Double` (or vice versa), triggering over-/underflow.

I'm seeing on the reading side that it's hitting the Double section of `org.apache.avro.generic.GenericDatumReader`, aka this:

```
case DOUBLE:
      return in.readDouble();
```

so I'm now looking at ObjectWriter to see how the bytes look and compare it to the other ones that do pass when using doubles.

**Comment by rdifrango** [comment]
To your point, with `Apache to Apache with Jackson schema` or `Jackson to Apache with Jackson schema` the following do work fine:

* Float
* Integers
* Strings
* Longs

The one that fails with different values is:

* Double

The ones not working at all are:

* Shorts `java.lang.ClassCastException: class java.lang.Short cannot be cast to class java.lang.Integer (java.lang.Short and java.lang.Integer are in module java.base of loader 'bootstrap')`

* Characters `java.lang.ClassCastException: class java.lang.Character cannot be cast to class java.lang.Integer (java.lang.Character and java.lang.Integer are in module java.base of loader 'bootstrap')`

* Bytes - `java.lang.ClassCastException: class java.lang.Byte cannot be cast to class java.lang.Integer (java.lang.Byte and java.lang.Integer are in module java.base of loader 'bootstrap')`

**Comment by cowtowncoder** [comment]
Sounds like some level of casting would be needed, somewhere. But not quite sure how/why breakage; I guess Avro Codec started using more accurate Java types, maybe, for its binding (or more generic?).

I know above is not super helpful, just thinking out aloud I guess.

**Comment by rdifrango** [comment]
> Sounds like some level of casting would be needed, somewhere. But not quite sure how/why breakage; I guess Avro Codec started using more accurate Java types, maybe, for its binding (or more generic?).
> 
> I know above is not super helpful, just thinking out aloud I guess.

Well, for the double case, I at least tracked it down to here and it's close to what you thought, they're converting the Double to a floatValue and when it's called it returns either `0` or `Infinity` which feels like a bug in Avro to me:

https://github.com/apache/avro/blob/main/lang/java/avro/src/main/java/org/apache/avro/generic/PrimitivesArrays.java#L549-L554

**Comment by cowtowncoder** [comment]
@rdifrango Thank you for tracking that down, yes, symptoms fit the problem. `float` range not big enough to represent MIN/MAX `double`, obviously, so gets "rounded"/truncated to 0 / Inf.

Could you file a bug (and maybe even PR) against Avro-lib, that definitely looks like a straight-forward bug, possibly copy-paste error?

**Comment by rdifrango** [comment]
https://issues.apache.org/jira/browse/AVRO-4110

**Comment by cowtowncoder** [comment]
Thank you @rdifrango !

**Comment by rdifrango** [comment]
> Thank you @rdifrango !

No worries and I'm working on the PR to fix that.

I also think the following change is what caused this and is the one causing the failures with `Short`, `Character`, and `Byte` test as well:

https://github.com/apache/avro/pull/2389, specifically [this](https://github.com/apache/avro/pull/2389#discussion_r1777564377) comment.

**Comment by rdifrango** [comment]
@cowtowncoder, the first PR is in:

https://github.com/apache/avro/pull/3292

Now to prove my theory on the PR that may have caused the other failures.

**Comment by cowtowncoder** [comment]
@rdifrango Looks like some fixes were merged, but your PR not. That's too bad. No new 1.12.x releases either. So still waiting... can hopefully upgrade for 3.0.0-rc3 if new Avro lib is released soon enough.

**Comment by rdifrango** [comment]
Agreed the fix that was merged was only a partial one so mine is necessary but stalled despite myself and others asking.

I also believe that the change that introduced this issue is the root of the other ones I'm seeing.

**Comment by cowtowncoder** [comment]
Looks like 1.12.1 was released a week ago: https://mvnrepository.com/artifact/org.apache.avro/avro

@rdifrango Did your fix(es) get merged in that release?

**Comment by rdifrango** [comment]
As far as I know it yes.

**Comment by cowtowncoder** [comment]
@rdifrango So we might be able to try upgrading Avro lib version? At least in 3.x (for 3.1.0) and maybe 2.x (for 2.21.0)?

**Comment by rdifrango** [comment]
> [@rdifrango](https://github.com/rdifrango) So we might be able to try upgrading Avro lib version? At least in 3.x (for 3.1.0) and maybe 2.x (for 2.21.0)?

Sorry just getting back to this now, I'll look at applying this to the 3.x branch as our project has moved onto it and this is a blocker for us as the Kafka clients are moving to Avro 1.12.x

**Comment by cowtowncoder** [comment]
With 1.12.1 compilation fails with this:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.14.1:compile (default-compile) on project jackson-dataformat-avro: Compilation failure: Compilation failure: 
[ERROR] /Users/tatu/jackson/jackson3-dataformats-binary/avro/src/main/java/tools/jackson/dataformat/avro/AvroMapper.java:[284,54] cannot find symbol
[ERROR]   symbol:   method setValidate(boolean)
[ERROR]   location: class org.apache.avro.Schema.Parser
[ERROR] /Users/tatu/jackson/jackson3-dataformats-binary/avro/src/main/java/tools/jackson/dataformat/avro/AvroMapper.java:[299,50] cannot find symbol
[ERROR]   symbol:   method setValidate(boolean)
[ERROR]   location: class org.apache.avro.Schema.Parser
[ERROR] /Users/tatu/jackson/jackson3-dataformats-binary/avro/src/main/java/tools/jackson/dataformat/avro/AvroMapper.java:[311,50] cannot find symbol
[ERROR]   symbol:   method setValidate(boolean)
[ERROR]   location: class org.apache.avro.Schema.Parser
```

which is unfortunate.

**Comment by cowtowncoder** [comment]
But as per Claude:

```
  The Problem                                                                                                      
                                                                                                                   
  In AvroMapper.java (lines 284, 299, 311), the code calls:                                                        
                                                                                                                   
  new Schema.Parser().setValidate(true).parse(...)                                                                 
                                                                                                                   
  This method existed in Avro 1.11.x to enable/disable "name validation" (checking that schema names comply with   
  Avro naming rules). In Avro 1.12.0, this method was removed entirely because name validation is now always       
  enabled and cannot be disabled.                                                                                  
                                                                                                                   
  The Fix                                                                                                          
                                                                                                                   
  Since setValidate(true) was enabling validation that is now always-on by default, the fix is simple: remove the  
  .setValidate(true) calls. The code should just be:                                                               
                                                                                                                   
  new Schema.Parser().parse(...)                                                                                   
                                                                                                                   
  This needs to be done in three places in AvroMapper.java:                                                        
  - Line 284 (schemaFrom(InputStream in))                                                                          
  - Line 299 (schemaFrom(String schemaAsString))                                                                   
  - Line 311 (schemaFrom(File schemaFile))                                                                         
                                                                                                                   
  Sources                                                                                                          
                                                                                                                   
  - https://github.com/FasterXML/jackson-dataformats-binary/issues/514                                             
  - https://avro.apache.org/docs/1.12.0/api/java/org/apache/avro/Schema.Parser.html - shows setValidate is missing 
  - https://avro.apache.org/docs/1.11.0/api/java/org/apache/avro/Schema.Parser.html - shows setValidate was present
                                                   
```

**Comment by cowtowncoder** [comment]
Ok so fix looks easy enough -> PR #644.

**Comment by rdifrango** [comment]
Great...I was looking at the same fix!

It should be the same in 2.x and 3.x.

**Comment by cowtowncoder** [comment]
2.x is bit trickier, wrt JDK 11 baseline. And 2.x going into maintenance mode...

**Comment by cowtowncoder** [comment]
Will start with 3.x for upcoming 3.1.0-rc1 -- have more time to consider 2.x since 2.21.0 was released 2 days ago (and upgrade ideally should in a minor release).

But I'll see if just removing `.setValidate()` calls was possible to allow users to upgrade avro lib.

**Comment by rdifrango** [comment]
Sounds good thank you...I can test the 3.1 RC when it's ready.

**Comment by cowtowncoder** [comment]
2.21(.1) patched via #645 so manual override should be possible; just not automatic (yet anyway).

**Comment by cowtowncoder** [comment]
@rdifrango hopefully within 1 week. Until then, `3.1.0-rc1-SNAPSHOT` should work too if you can access it via Sonatype Central Snapshots.
