### ISSUE TITLE
Cannot resolve inner types in protoc definitions

### ISSUE THREAD

**Issue by knoguchi** [FasterXML/jackson-dataformats-binary#73]
When messages are defined as below, the parser failed to resolve t1.i1 type.

```
package mypackage;

message t1 {
        message i1 {
                optional uint32 x = 1;
                optional uint32 y = 2;
        }
}

message t2 {
        optional t1.i1 z = 1;
}
```

Error

```
Exception in thread "main" java.lang.IllegalArgumentException: Unknown protobuf field type 't1.i1' for field 'z' of MessageType 't2' (known enum types: ; known message types: t1, t2)
	at com.fasterxml.jackson.dataformat.protobuf.schema.TypeResolver._resolve(TypeResolver.java:141)
	at com.fasterxml.jackson.dataformat.protobuf.schema.TypeResolver.resolve(TypeResolver.java:93)
	at com.fasterxml.jackson.dataformat.protobuf.schema.NativeProtobufSchema.forType(NativeProtobufSchema.java:67)
	at com.fasterxml.jackson.dataformat.protobuf.schema.ProtobufSchemaLoader.load(ProtobufSchemaLoader.java:51)
```

**Comment by cowtowncoder** [comment]
Unfortunately I can not reproduce this: if I load schema you specify, there is no error.
This could either be due to version you are using (if it's old, could be fixed), or your code does something different that what I have. My test has:

```java
 ProtobufSchema schema = MAPPER.schemaLoader()
                .load(new StringReader(SCHEMA_STR));
```

with schema s above.

**Comment by knoguchi** [comment]
Thanks for the quick response.   I simplified my test code.   The only difference is that I specified the rootType "t2".   I'm using the HEAD of the 2.8 branch pulled today.

```
ProtobufSchema schema = MAPPER.schemaLoader()
                .load(new StringReader(SCHEMA_STR), "t2");
```

And then the stacktrace

```
Exception in thread "main" java.lang.IllegalArgumentException: Unknown protobuf field type 't1.i1' for field 'z' of MessageType 't2' (known enum types: ; known message types: t1, t2)
	at com.fasterxml.jackson.dataformat.protobuf.schema.TypeResolver._resolve(TypeResolver.java:141)
	at com.fasterxml.jackson.dataformat.protobuf.schema.TypeResolver.resolve(TypeResolver.java:94)
	at com.fasterxml.jackson.dataformat.protobuf.schema.NativeProtobufSchema.forType(NativeProtobufSchema.java:67)
	at com.fasterxml.jackson.dataformat.protobuf.schema.ProtobufSchemaLoader.load(ProtobufSchemaLoader.java:97)
```

**Comment by cowtowncoder** [comment]
Thanks! Yes, that does trigger the issue for me too, for 2.8 branch and probably `master` too.

**Comment by cowtowncoder** [comment]
(accidental fix by github, due to comment)

**Comment by knoguchi** [comment]
I am trying to understand the code base, and I saw the type resolver tries to find the name recursively but it's a little hard for me to fix.   I wonder if it's easy for you to fix.

My idea is to calculate fully qualified name at the time of parsing so that the type resolver does not have to traverse the type tree.  Do you think it's sane approach?

**Comment by knoguchi** [comment]
I just noticed FieldElement class does not have `.qufaliedName()` unlike TypeElement class.  So we still need type resolution for the fields.

Looks like the [Wire](https://github.com/square/wire/), the successor of the [ProtoParser](https://github.com/square/protoparser), was created for [the very reason](https://publicobject.com/2015/07/13/protoparser-is-going-away/).

I hope someday ProtoParser will be replaced for Wire in this project.   For now, I decided to use other solutions.   Thanks.

**Comment by cowtowncoder** [comment]
@knoguchi I was hoping to fix this along with #140, as I now understand the issue finally (it has been a while but I got back to here). Scoped resolution works with latest fixes but only in certain orders of traversal; I'll have to rewrite code a bit. Should get done for 2.10.0 however, need to get 2.9.8 out first.
