### ISSUE TITLE
[protobuf] can't deserialize packed repeated field

### ISSUE THREAD

**Issue by knoguchi** [FasterXML/jackson-dataformats-binary#76]
Packed repeated field failed to deserialize the Protobuf bytes.
```
message t1 {
        repeated uint32 report_code = 1 [packed=true];
}
```

The error:

```
com.fasterxml.jackson.core.JsonParseException: Incompatible wire type (0x2) for field 'report_code': not valid for field of type VINT32_STD (expected 0x0)

	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.dataformat.protobuf.ProtobufParser._reportErrorF(ProtobufParser.java:2455)
	at com.fasterxml.jackson.dataformat.protobuf.ProtobufParser._reportIncompatibleType(ProtobufParser.java:2461)
	at com.fasterxml.jackson.dataformat.protobuf.ProtobufParser.nextFieldName(ProtobufParser.java:1110)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:210)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1626)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1237)
```

When the packed is true, the wire type 0x2 is actually correct as the official document explained in the [Message Structure wire type](https://developers.google.com/protocol-buffers/docs/encoding) section.

Here is the [test code](https://gist.github.com/knoguchi/7a94a8aaec5902d34a6ef1d93e0b31b9). `PackedWrapper` class was generated by `protoc`.

**Comment by cowtowncoder** [comment]
Thank you for submitting this, and fix too. I'll have a look because one thing I don't understand is why existing tests didn't catch this -- packed types are tested, but test coverage is not as extensive as it should.

**Comment by cowtowncoder** [comment]
Ah ok. I think the problem is that since tests use generator, which encodes packed fields incorrectly as you point out (and I think you are right there), no problem is noticed. It's only when using actual packed encoding that shows the problem.

But wouldn't this also suggest there's similar problem on generator/encoding side too?
Meaning that encoder should use type `2` as well.
For backwards compatibility I think that checks by decoder should probably accept both types (as per fix); but generator should revert to proper usage in 2.9 (but not earlier).

**Comment by knoguchi** [comment]
I was trying to parse the PB from my production system.  That was how I noticed the deserializing problem.  Yes, I believe the generator/encoder side problem as well.

**Comment by cowtowncoder** [comment]
@knoguchi Ok. Yes, let's start by letting parser accept proper type (for 2.8 too), and then worry about generator for `master` (2.9).
