### ISSUE TITLE
[protobuf] possible binary decoder problem

### ISSUE THREAD

**Issue by knoguchi** [FasterXML/jackson-dataformats-binary#89]
I'm having problem with deserializing a PB binary that the protoc generated.
Here is the step to reproduce the problem.  I'm not 100% confident in the way I tested having `reserved` fields commented out (explained later).   The official protobuf-java has no problem decoding the PB. 

1. clone https://github.com/google/protobuf project
2. create the descriptor file of the unit test.
`protoc -o unittest_proto3.desc  google/protobuf/unittest_proto3.proto google/protobuf/unittest_import_proto3.proto google/protobuf/unittest_import_public_proto3.proto`
3. the descriptor is actually a PB defined by [descriptor.proto](https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto).  Comment out `reserved` fields.  (not sure if it's safe though).
4. run [test case](https://gist.github.com/knoguchi/da4125b66ca20e3b0d1f26f35ac2d6ea)

```
com.fasterxml.jackson.core.JsonParseException: Too long tag VInt: fifth byte 0xff
 at [Source: (BufferedInputStream); line: -1, column: 3446]

	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1771)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:651)
	at com.fasterxml.jackson.dataformat.protobuf.ProtobufParser._reportErrorF(ProtobufParser.java:2482)
	at com.fasterxml.jackson.dataformat.protobuf.ProtobufParser._reportTooLongVInt(ProtobufParser.java:2497)
	at com.fasterxml.jackson.dataformat.protobuf.ProtobufParser._decodeVInt(ProtobufParser.java:2217)
	at com.fasterxml.jackson.dataformat.protobuf.ProtobufParser._readNextValue(ProtobufParser.java:798)
	at com.fasterxml.jackson.dataformat.protobuf.ProtobufParser.nextToken(ProtobufParser.java:671)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:249)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:434)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:434)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:434)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:434)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1613)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1183)
	at com.fasterxml.jackson.dataformat.protobuf.schema.DeserializeTest.testDeserialize
```

**Comment by knoguchi** [comment]
Closing this issue for now.  I can't guarantee that the .proto and the PB bytes use the same exact schema.
